src/tweetme/account_app/urls.py
from django.conf.urls import url
from .views import UserDetailView, UserFollowView

app_name='profile_app'
urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', UserDetailView.as_view(), name='user_detail'),
    url(r'^(?P<username>[\w-]+)/follow/$', UserFollowView.as_view(), name='user_follow'),
]


src/tweetme/tweetme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from tweets_app import views
from .views import RegisterView, SearchView
from hashtags_app.views import HashTagView
from hashtags_app.api.views import HashTagAPIView
urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', views.TweetList.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    # tweets_app
    url(r'^tweet/', include('tweets_app.urls')),
    url(r'^api/tweet/', include('tweets_app.api.urls', namespace='tweet-api')),
    #search
    url(r'^search/$', SearchView.as_view(), name='search'),
    # account_app
    url(r'^profile/', include('account_app.urls')),
    url(r'^api/', include('account_app.api.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # hashtags_app
    url(r'^tags/(?P<hashtag>[\w-]+)/$', HashTagView.as_view(), name='hashtag'),
    url(r'^api/tags/(?P<hashtag>[\w-]+)/$', HashTagAPIView.as_view(), name='hashtag'),
    # login,logout,register
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tweetme/tweets_app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from .views import TweetList, TweetDetail, TweetCreate, TweetUpdate, TweetDelete, Retweet

app_name='tweet_app'

urlpatterns = [
    url(r'^list/$', TweetList.as_view(), name='tweet_list'),
    url(r'^(?P<pk>\d+)/$', TweetDetail.as_view(), name='tweet_detail'),
    url(r'create/$', TweetCreate.as_view(), name='tweet_create'),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdate.as_view(), name='tweet_update'),
    url(r'^(?P<pk>\d+)/delete/$', TweetDelete.as_view(), name='tweet_delete'),
    url(r'^(?P<pk>\d+)/retweet/$', Retweet.as_view(), name='retweet'),
    
]

src/tweetme/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%}Tweet.co {%endblock%}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">


</head>

<body>
    {%include 'navbar.html'%}
    {%block content%} {%endblock%}
    {%include 'tweets_app/replymodal.html'%}


    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src='{%static "js/bootstrap.js"%}'> </script>
    {%block script%}{%endblock script%}
    <script>
        $(document).ready(function () {
            var typingTimer;
            var doneInterval = 1500;
            var searchInput = $("#navbar-search-form input[type=search]");
            var searchQuery;

            searchInput.keyup(function (event) {
                searchQuery = $(this).val()
                typingTimer = setTimeout(doneSearchTyping, doneInterval)

            })


            function doneSearchTyping() {
                if (searchQuery) {
                    var url = '/search/?q=' + searchQuery
                    document.location.href = url;
                }
            }
        })

        // < !--fetch tweet-- >

        // this functions helps you get the search query q
        function getParameterByName(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, '\\$&');
            var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, ' '));
        }
        function loadTweetContainer(tweetContainerId, fetchOne) {
            var query = getParameterByName('q');
            var tweetList = [];
            var createApiTweet = "/api/tweet/create/";
            var tweetContainer;
            if (tweetContainerId) {
                tweetContainer = $("#" + tweetContainerId)
            } else {
                tweetContainer = $("#tweet-container")
            }
            var initialUrl = tweetContainer.attr("data-url") || "/api/tweet/";
            function updateHashLinks() {
                $(".media-body").each(function (data) {
                    // #hashtag
                    var hashtagRegex = /#([\d\w-]+)/g
                    var newText = $(this).html().replace(hashtagRegex, "<a href='/tags/$1/'>#$1</a>")
                    $(this).html(newText)

                    // @user
                    var userRegex = /@([\d\w-]+)/g
                    var newText = $(this).html().replace(userRegex, "<a href='/tags/$1/'>@$1</a>")
                    $(this).html(newText)
                })
            }

            // retweet function
            $(document.body).on("click", ".retweet", function (event) {
                event.preventDefault()
                var url = $(this).attr("href")
                console.log(url)
                $.ajax({
                    url: url,
                    method: "GET",
                    success: function (data) {
                        if (initialUrl == '/api/tweet/') {
                            attachTweet(data, true)
                            updateHashLinks()
                        }
                    },
                    error: function (data) {
                        console.log('bad')
                    }
                })
            })

            // Like toggle
            $(document.body).on("click", ".like-btn", function (event) {
                event.preventDefault()
                var this_ = $(this)
                var tweetId = this_.attr('data-id')
                var likeUrl = '/api/tweet/' + tweetId + '/like'


                $.ajax({
                    url: likeUrl,
                    method: "GET",
                    success: function (data) {
                        if (data.liked) {
                            this_.text("Liked");

                        } else {
                            this_.text("Unliked");
                        }
                    },
                    error: function (data) {
                        console.log('it doesnt work')
                    }
                })
            })

            // Reply tweet
            $(document.body).on("click", ".reply-btn", function (event) {
                event.preventDefault()
                var this_ = $(this)
                var parentId = this_.attr('data-id')
                var username = this_.attr('data-user')
                var parentUsername = (this_).parent().parent().find("#data-parent").text()
                var content = this_.parent().parent().find("#content").text()
                $("#replyModal").modal({})
                if (parentUsername) { $("#modalReply").val('@' + parentUsername + ' ') } else { $("#modalReply").val('@' + username + ' ') }
                $("#replyModal").on('shown.bs.modal', function (event) {
                    $(".tweet-form textarea").focus()

                })
                $(".tweet-form textarea").after('<input type="hidden" name="parent_id" value ="' + parentId + '">')
                $(".tweet-form textarea").after('<input type="hidden" name="reply" value ="true">')
                $("#replyModal #replyModalLabel").text('Reply to: ' + content)
            })

            // format the tweets
            function formatTweet(tweetValue) {
                var replyId = tweetValue.pk
                if (tweetValue.parent) {
                    replyId = tweetValue.parent.pk
                }

                // show like or liked after loading the page
                var verbLike;
                if (tweetValue.did_like) { verbLike = 'Liked' } else { verbLike = 'Like' }

                // singel out tweet
                var singelOut = '<div class="media-body">'
                if (fetchOne == tweetValue.pk) { singelOut = '<div class="media-body media-focus">' }

                // check if the tweet was retweeted
                var preContent = ''
                var isReply = tweetValue.reply


                if (tweetValue.parent && !isReply) {
                    tweetValue.pk = tweetValue.parent.pk
                    tweetValue.like_count = tweetValue.parent.like_count
                    preContent = '<p class="mb-0 gray-text font-italic ">Retweet via <a href="' + tweetValue.parent.author_url + '"><span id="data-parent">' + tweetValue.parent.author.username + '</span></a></p>'
                } else if (tweetValue.parent && isReply) {
                    tweetValue.pk = tweetValue.parent.pk
                    tweetValue.like_count = tweetValue.parent.like_count
                    preContent = '<p class="mb-0 gray-text font-italic">Reply to @<a href="' + tweetValue.parent.author_url + '"><span id="data-parent">' + tweetValue.parent.author.username + '</span></a></p>'
                }


                // author box
                console.log(tweetValue)
                var tweetAuthorContent = '<div class= "col-sm-3" ><p class="mb-0 text-center"><a href="' + tweetValue.author_url + '">' + tweetValue.author.username + '</a></p><p class="text-center mb-0">' + tweetValue.time_display + '</p></div>'

                // tweet box
                var tweetContent = '<div class="col-sm-9"><div class="media">' + singelOut + preContent + '<p class="mb-0 align-middle"><span id="content">' + tweetValue.content + '</span> (<a href="' + tweetValue.content_url + '">View</a> | <a class="retweet" href="' + tweetValue.retweet_url + '">Retweet</a> | <a class="like-btn" data-id="' + tweetValue.pk + '" href="' + tweetValue.pk + '">' + verbLike + '(' + tweetValue.like_count + '</a>) | <a class="reply-btn" data-id="' + replyId + '" data-user ="' + tweetValue.author.username + '" href="#">Reply</a>)</p></div></div></div>'

                var container = '<div class="row my-3">' + tweetAuthorContent + tweetContent + '</div><div class="row"><div class="col-3"></div><div class="col-9"><hr></div></div>'
                return container
            }


            function attachTweet(tweetValue, prepend) {
                var tweetFormattedHtml;
                tweetFormattedHtml = formatTweet(tweetValue)

                var tweetHTML;
                if (prepend == true) {
                    tweetContainer.prepend(tweetFormattedHtml)
                } else {
                    tweetContainer.append(tweetFormattedHtml)
                }
            }

            function parseTweets() {
                if (tweetList == 0) {
                    tweetContainer.text('No tweets currently found.')
                } else {
                    $.each(tweetList, function (key, value) {
                        attachTweet(value, false)

                    })
                }
            }

            var nextTweetUrl;
            // fetch all tweets
            function fetchTweet(url) {
                var fetchUrl;
                if (!url) {
                    fetchUrl = initialUrl
                    console.log(fetchUrl)
                } else {
                    fetchUrl = url
                    console.log(fetchUrl)
                }
                $.ajax({
                    url: fetchUrl,
                    data: { "q": query },
                    method: "GET",

                    success: function (data) {
                        tweetList = data.results
                        if (data.next) { nextTweetUrl = data.next } else { $("#loadmore").css('display', 'none') }
                        parseTweets()
                        updateHashLinks()
                    },
                    error: function (data) {
                        console.log('error')
                    },
                });
            }

            // fetch  tweet detail
            function fetchSingle(fetchOne) {
                var fetchUrl = '/api/tweet/' + fetchOne + '/'
                $.ajax({
                    url: fetchUrl,
                    method: "GET",

                    success: function (data) {
                        tweetList = data.results
                        if (data.next) { nextTweetUrl = data.next } else { $("#loadmore").css('display', 'none') }
                        parseTweets()
                        updateHashLinks()
                    },
                    error: function (data) {
                        console.log('error')
                    },
                });
            }

            // fetch all tweets or fetch detail
            if (fetchOne) {
                fetchSingle(fetchOne)
            } else {
                fetchTweet()
            }

            // load more tweet, go to next api page
            $("#loadmore").click(function (event) {
                event.preventDefault()
                if (nextTweetUrl) { fetchTweet(nextTweetUrl) }
            })

            // count characters of form
            var charsStart = 150
            var charsCurrent = 0
            $(".tweet-form").append("<span id='tweetCharLeft'>" + charsStart + "</span>")

            // count characters of form, change text colors.
            $(".tweet-form textarea").keyup(function (event) {
                charsCurrent = charsStart - $(this).val().length
                var charTag = $(".tweet-form").find("#tweetCharLeft")
                charTag.text(charsCurrent)
                if (charsCurrent > 0) {
                    charTag.addClass('green-text')
                } else if (charsCurrent == 0) {
                    charTag.removeClass('green-text')
                } else if (charsCurrent < 0) {
                    charTag.addClass('red-text')
                }

            })



            $(".tweet-form").submit(function (event) {
                event.preventDefault()
                var this_ = $(this)
                var formData = this_.serialize()
                console.log(formData)
                if (charsCurrent >= 0) {
                    $.ajax({
                        url: createApiTweet,
                        data: formData,
                        method: "POST",

                        success: function (data) {
                            this_.find("textarea").val("")
                            attachTweet(data, true)
                            updateHashLinks()
                            $('#replyModal').modal('hide')
                        },
                        error: function (data) {
                            console.log("error")
                        }
                    })
                } else {
                    console.log('Cannot send')
                }
            })
        }

    </script>
</body>

</html>

src/tweetme/templates/home.html
fuck

src/tweetme/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{%url 'tweet_app:tweet_list'%}">Tweet.co</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto ml-3">
        <li>
          {%include 'tweets_app/search_form.html'%}
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {%if request.user.is_authenticated%}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ request.user.profile.get_absolute_url }}">Profile</a>
            <a class="dropdown-item" href="{%url 'logout'%}">Log Out</a>

          </div>
        </li>
        {%else%}
        <li class="nav-item active mr-3">
          <a class="nav-link" href="{%url 'login'%}">Login</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'register'%}">Register</a>
        </li>
        {%endif%}
      </ul>

    </div>
  </div>
</nav>

src/tweetme/templates/search.html
{%extends 'base.html'%}

{%block title%}
{{block.super}}List{%endblock%}

{%block script%}
<script>
    $(document).ready(function () {
        loadTweetContainer("tweet-container")
    })
</script>

{%endblock%}

{%block content%}

{%if request.GET.q%}
<div class="container">
    <div class="row">
        <div class="col mt-5 lead">
            <p>Result for: {{request.GET.q}}</p>
        </div>

    </div>
    <hr>
    <div class="row">
        <div class="col-sm-9">
            <h3 class='d-5 py-5 display-4 text-center'>Tweets</h3>

            <!-- Use ajax to extract tweet list -->
            <div id="tweet-container" data-url="/api/tweet/search/"></div>
            <div class="row my-2">
                <div class="col-sm-3">
                    <p class="mb-0 text-center"><a href="" id="loadmore" class="text-center">Load more tweets</a></p>
                </div>
            </div>
            {%else%}
            <p>No tweets</p>
            {%endif%}
        </div>

        <div class="col sm-3">
            <h3 class='d-5 py-5 display-4 text-center'>Users</h3>
            <ol>
                {%for user in user_list%}
                <li>
                    <a href="{%url 'profile_app:user_detail' username=user.username%}">{{user.username}}</a>
                </li>
                {%empty%}
                No users currently found
                {%endfor%}
            </ol>

        </div>
    </div>
</div>

<!-- <a href="" id="loadmore" class="text-center">Load more tweets</a> -->


{%endblock%}